import AppKit
import CryptoKit
import GobblCore
import Observation

/// Clipboard history. Polls the pasteboard's change count twice a second (a
/// counter read — there is no change notification), skips anything password
/// managers mark as concealed or transient, and stores history on disk only.
@MainActor @Observable
final class ClipboardModel {
    static let shared = ClipboardModel()

    private(set) var history: ClipboardHistory

    @ObservationIgnored private var timer: Timer?
    @ObservationIgnored private var lastChange = NSPasteboard.general.changeCount
    @ObservationIgnored private let thumbnails = NSCache<NSString, NSImage>()

    static let directory: URL = {
        let dir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Gobbl/Clipboard", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }()

    private static var storeURL: URL { directory.appendingPathComponent("history.json") }

    /// nspasteboard.org markers: passwords, one-off and generated content.
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType",
    ]

    private init() {
        history = (try? Data(contentsOf: Self.storeURL))
            .flatMap { try? JSONDecoder().decode(ClipboardHistory.self, from: $0) } ?? ClipboardHistory()
    }

    var enabled: Bool { UserDefaults.standard.object(forKey: "clipboardEnabled") as? Bool ?? true }

    func start() {
        guard timer == nil else { return }
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        t.tolerance = 0.25
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    // MARK: Actions

    func copy(_ item: ClipItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.kind {
        case .text:
            pb.setString(item.text, forType: .string)
        case .link:
            pb.setString(item.text, forType: .string)
            pb.setString(item.text, forType: .URL)
        case .file:
            pb.writeObjects(item.text.split(separator: "\n").map { NSURL(fileURLWithPath: String($0)) })
        case .image:
            if let image = NSImage(contentsOf: imageURL(for: item)) { pb.writeObjects([image]) }
        }
        // Our own write: don't record it as a new copy, just move it to the top.
        lastChange = pb.changeCount
        var moved = item
        moved.date = Date()
        discard(history.record(moved))
        save()
        HUDModel.shared.show(.init(symbol: "doc.on.clipboard.fill", label: "Copied"))
    }

    func togglePin(_ item: ClipItem) {
        history.togglePin(item.id)
        save()
    }

    func remove(_ item: ClipItem) {
        if let removed = history.remove(item.id) { discard([removed]) }
        save()
    }

    func clearUnpinned() {
        discard(history.clearUnpinned())
        save()
    }

    func imageURL(for item: ClipItem) -> URL { Self.directory.appendingPathComponent(item.text) }

    func thumbnail(for item: ClipItem) -> NSImage? {
        let key = item.text as NSString
        if let cached = thumbnails.object(forKey: key) { return cached }
        guard let image = NSImage(contentsOf: imageURL(for: item)) else { return nil }
        thumbnails.setObject(image, forKey: key)
        return image
    }

    // MARK: Capture

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount
        guard enabled else { return }
        capture(pb)
    }

    private func capture(_ pb: NSPasteboard) {
        let types = pb.types ?? []
        guard !types.contains(where: { Self.ignoredTypes.contains($0.rawValue) }) else { return }
        let app = NSWorkspace.shared.frontmostApplication?.localizedName
        var item: ClipItem?

        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            item = ClipItem(kind: .file, text: urls.map(\.path).joined(separator: "\n"), sourceApp: app)
        } else if let string = pb.string(forType: .string),
                  !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            let isLink = !trimmed.contains(where: \.isWhitespace)
                && ["http", "https"].contains(URL(string: trimmed)?.scheme?.lowercased() ?? "")
            item = ClipItem(kind: isLink ? .link : .text, text: String(string.prefix(50_000)), sourceApp: app)
        } else if let data = pb.data(forType: .png) ?? pb.data(forType: .tiff),
                  let rep = NSBitmapImageRep(data: data),
                  let png = rep.representation(using: .png, properties: [:]) {
            let digest = SHA256.hash(data: png).map { String(format: "%02x", $0) }.joined()
            let name = history.item(matching: "image:\(digest)")?.text ?? "\(UUID().uuidString).png"
            let url = Self.directory.appendingPathComponent(name)
            if !FileManager.default.fileExists(atPath: url.path) { try? png.write(to: url) }
            item = ClipItem(kind: .image, text: name, digest: digest, sourceApp: app)
        }

        guard let item else { return }
        discard(history.record(item))
        save()
        PetModel.shared.send(.clipboardCopied)
    }

    private func discard(_ items: [ClipItem]) {
        for item in items where item.kind == .image {
            try? FileManager.default.removeItem(at: imageURL(for: item))
            thumbnails.removeObject(forKey: item.text as NSString)
        }
    }

    private func save() {
        guard let data = try? JSONEncoder().encode(history) else { return }
        try? data.write(to: Self.storeURL, options: .atomic)
    }
}
